server:
  port: 6007

spring:
  profiles:
    active: local
  application:
    name: springboot_jpa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study
    username: study
    password: Study1234!@
  jpa:
    hibernate:
      # ddl-auto: create-drop
      # ddl-auto: create
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    # org.hibernate.orm.jdbc.bind: trace